### ISSUE TITLE
Labelling issues + Pulls

### ISSUE THREAD

**Issue by pedromorgan** [mikidown/mikidown#79]
Can we start labelling issues and also add.. new labels eg

```
topic-systray
topic-preview
topic-markdown
topic-generate
```

**Comment by ShadowKyogre** [comment]
This is a good idea. I've reorganized the labels with the following syntax:

- `type-{issuetype}`
- `os-{linux,windows}`
- `p-{allthethingsformikidowncode}`
- needs-user-input (( the only odd one out of bunch ))

It'll take me a while to sort through the old tickets and appropriately label them.

**Comment by pedromorgan** [comment]
done
